# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4bf0033d3bdb847ba58a26c4b1cfb0d787edc9fcc42d78cec21440f3054f9195fc14c6bfefe091827676deac48e682dcac9f29980ae7526bf257fe31aa06891

test:
  secret_key_base: 30fc013ca010571de28d24b60cf8aa924076dffcc7cca20f84709f5604a60e25e9cad1e60aac1d8092d9b4323bc4908524101c2783f8f4f8c7779f54bbcd16a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
